# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='auth.User', max_length=20),
        ),
    ]
